server:
  port: 8022
#spring:
#  h2:
#    console:
#      path: /console
#      enabled: true
#      settings:
#        web-allow-others: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pixogram
    username: admin
    password: Manu12345

  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    
  application:
    name: media-service
    
# eureka client    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    
   
