server:
  port: 8021
#spring:
#  h2:
#    console:
#      path: /console
#      enabled: true
#      settings:
#        web-allow-others: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pixogram
    username: admin
    password: Manu12345

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    
  application:
    name: user-service

# eureka client
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    
   
